# Form implementation generated from reading ui file '.\Home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow.resize(1495, 845)
        MainWindow.setStyleSheet("border-image: url(:/SRC/SRC/Department Examination Management Application Light Version.png)0 0 0 0 stretch stretch;;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(30, 10, 171, 101))
        self.Logo.setStyleSheet("border-image: url(:/SRC/SRC/Logo.png);")
        self.Logo.setText("")
        self.Logo.setObjectName("Logo")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(70, 120, 1341, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1341, 611))
        self.frame.setMaximumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("display:block;\n"
"border-image: url(:/SRC/SRC/transbg.png);\n"
"border-radius: 20px;\n"
"warp:no-warp;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Department_Button_2 = QtWidgets.QPushButton(parent=self.frame)
        self.Department_Button_2.setGeometry(QtCore.QRect(370, 350, 231, 241))
        self.Department_Button_2.setAcceptDrops(True)
        self.Department_Button_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-image: url(:/SRC/SRC/Department (2).png);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(100, 170, 255);\n"
"border-image:url(:/SRC/SRC/Department.png);\n"
"}\n"
"")
        self.Department_Button_2.setText("")
        self.Department_Button_2.setObjectName("Department_Button_2")
        self.Department_Button_3 = QtWidgets.QPushButton(parent=self.frame)
        self.Department_Button_3.setGeometry(QtCore.QRect(890, 80, 231, 241))
        self.Department_Button_3.setAcceptDrops(True)
        self.Department_Button_3.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-image: url(:/SRC/SRC/Department (2).png);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(100, 170, 255);\n"
"border-image:url(:/SRC/SRC/Department.png);\n"
"}\n"
"")
        self.Department_Button_3.setText("")
        self.Department_Button_3.setObjectName("Department_Button_3")
        self.Department_Button_4 = QtWidgets.QPushButton(parent=self.frame)
        self.Department_Button_4.setGeometry(QtCore.QRect(190, 80, 231, 241))
        self.Department_Button_4.setAcceptDrops(True)
        self.Department_Button_4.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-image: url(:/SRC/SRC/Department (2).png);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(100, 170, 255);\n"
"border-image:url(:/SRC/SRC/Department.png);\n"
"}\n"
"")
        self.Department_Button_4.setText("")
        self.Department_Button_4.setObjectName("Department_Button_4")
        self.Department_Button_5 = QtWidgets.QPushButton(parent=self.frame)
        self.Department_Button_5.setGeometry(QtCore.QRect(550, 80, 231, 241))
        self.Department_Button_5.setAcceptDrops(True)
        self.Department_Button_5.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-image: url(:/SRC/SRC/Department (2).png);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(100, 170, 255);\n"
"border-image:url(:/SRC/SRC/Department.png);\n"
"}\n"
"")
        self.Department_Button_5.setText("")
        self.Department_Button_5.setObjectName("Department_Button_5")
        self.Department_Button_6 = QtWidgets.QPushButton(parent=self.frame)
        self.Department_Button_6.setGeometry(QtCore.QRect(710, 350, 231, 241))
        self.Department_Button_6.setAcceptDrops(True)
        self.Department_Button_6.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-image: url(:/SRC/SRC/Department (2).png);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(100, 170, 255);\n"
"border-image:url(:/SRC/SRC/Department.png);\n"
"}\n"
"")
        self.Department_Button_6.setText("")
        self.Department_Button_6.setObjectName("Department_Button_6")
        self.Logo_2 = QtWidgets.QLabel(parent=self.frame)
        self.Logo_2.setGeometry(QtCore.QRect(-90, -120, 431, 361))
        self.Logo_2.setStyleSheet("border-image: url(:/SRC/SRC/LOgin Text (5).png);")
        self.Logo_2.setText("")
        self.Logo_2.setObjectName("Logo_2")
        self.Department_Button_2.raise_()
        self.Department_Button_3.raise_()
        self.Department_Button_5.raise_()
        self.Department_Button_6.raise_()
        self.Logo_2.raise_()
        self.Department_Button_4.raise_()
        self.frame.raise_()
        self.Logo.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1495, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
if __name__ == "__main__":
    import sys
    import SRC
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())