# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 700)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.511, y1:1, x2:0.488955, y2:0.449, stop:0 rgba(134, 162, 255, 255), stop:1 rgba(225, 206, 239, 255));")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(220, 160, 651, 391))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 37));")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(230, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(260, 20, 93, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 160, 241, 20))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(200, 140, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(200, 200, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 220, 241, 20))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(250, 270, 131, 41))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.955, x2:1, y2:1, stop:1 rgba(0, 0, 0, 0));\n"
"image: url(:/newPrefix/Department Examination Management Application Light Version Icon Pack/Login.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Sign in to Continue"))
        self.label.setText(_translate("Dialog", "LOGIN"))
        self.label_3.setText(_translate("Dialog", "USER ID"))
        self.label_4.setText(_translate("Dialog", "PASSWORD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
